/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LogServiceForm.java
 *
 * Created on Feb 24, 2011, 4:59:39 PM
 */

package border;

import entity.Member;
import entity.Provider;
import entity.Service;
import entity.ServiceRendered;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.math.BigDecimal;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

import org.jdesktop.application.Action;

/**
 *
 * @author Brandon
 */
public class LogServiceForm extends javax.swing.JFrame {

	private Date now;
    /**
	 * 
	 */
	private static final long serialVersionUID = -43572493282352303L;
	/** Creates new form LogServiceForm */
    public LogServiceForm() {
		now = new Date();
        initComponents();
        initX();
		dateRecordEnteredField.setValue((new SimpleDateFormat("MM-dd-yyyy HH:mm:ss")).format(now));
    }

	public LogServiceForm(String text) {
		this();
		memberNumberField.setText(text);
	}

	private void initX(){
		xServiceRendered.setVisible(false);
		xProvider.setVisible(false);
		xMember.setVisible(false);
		xService.setVisible(false);
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateServiceRenderedField = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        memberNumberField = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        commentsField = new javax.swing.JTextArea();
        serviceRenderedDateField = new javax.swing.JFormattedTextField();
        xProvider = new javax.swing.JLabel();
        xMember = new javax.swing.JLabel();
        xService = new javax.swing.JLabel();
        xServiceRendered = new javax.swing.JLabel();
        providerNumberField = new javax.swing.JFormattedTextField();
        serviceCodeField = new javax.swing.JFormattedTextField();
        dateRecordEnteredField = new javax.swing.JFormattedTextField();

        dateServiceRenderedField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        dateServiceRenderedField.setName("dateServiceRenderedField"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(pdx.edu.cs300_group9.DesktopApplication2.class).getContext().getResourceMap(LogServiceForm.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(pdx.edu.cs300_group9.DesktopApplication2.class).getContext().getActionMap(LogServiceForm.class, this);
        jButton2.setAction(actionMap.get("cancelButtonClicked")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N

        jButton4.setAction(actionMap.get("nextButtonClicked")); // NOI18N
        jButton4.setText(resourceMap.getString("jButton4.text")); // NOI18N
        jButton4.setName("jButton4"); // NOI18N

        try {
            memberNumberField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        memberNumberField.setName("memberNumberField"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        commentsField.setColumns(20);
        commentsField.setRows(5);
        //commentsField.setMaximumSize(100)
        commentsField.setName("commentsField"); // NOI18N
        jScrollPane1.setViewportView(commentsField);

        serviceRenderedDateField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("MM/dd/yyyy"))));
        serviceRenderedDateField.setText(resourceMap.getString("serviceRenderedDateField.text")); // NOI18N
        serviceRenderedDateField.setName("serviceRenderedDateField"); // NOI18N

        xProvider.setFont(resourceMap.getFont("xProvider.font")); // NOI18N
        xProvider.setForeground(resourceMap.getColor("xProvider.foreground")); // NOI18N
        xProvider.setText(resourceMap.getString("xProvider.text")); // NOI18N
        xProvider.setName("xProvider"); // NOI18N

        xMember.setFont(resourceMap.getFont("xMember.font")); // NOI18N
        xMember.setForeground(resourceMap.getColor("xMember.foreground")); // NOI18N
        xMember.setText(resourceMap.getString("xMember.text")); // NOI18N
        xMember.setName("xMember"); // NOI18N

        xService.setFont(resourceMap.getFont("xService.font")); // NOI18N
        xService.setForeground(resourceMap.getColor("xService.foreground")); // NOI18N
        xService.setText(resourceMap.getString("xService.text")); // NOI18N
        xService.setName("xService"); // NOI18N

        xServiceRendered.setFont(resourceMap.getFont("xServiceRendered.font")); // NOI18N
        xServiceRendered.setForeground(resourceMap.getColor("xService.foreground")); // NOI18N
        xServiceRendered.setText(resourceMap.getString("xServiceRendered.text")); // NOI18N
        xServiceRendered.setName("xServiceRendered"); // NOI18N

        providerNumberField.setFormatterFactory((new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("000000000")))));
        providerNumberField.setText(resourceMap.getString("providerNumberField.text")); // NOI18N
        providerNumberField.setName("providerNumberField"); // NOI18N

        serviceCodeField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("000000000"))));
        serviceCodeField.setText(resourceMap.getString("serviceCodeField.text")); // NOI18N
        serviceCodeField.setName("serviceCodeField"); // NOI18N

        dateRecordEnteredField.setEditable(false);
        dateRecordEnteredField.setText(resourceMap.getString("dateRecordEnteredField.text")); // NOI18N
        dateRecordEnteredField.setName("dateRecordEnteredField"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel5)
                        .addComponent(jLabel3)
                        .addComponent(jLabel1)
                        .addComponent(jLabel4)
                        .addComponent(jLabel6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(memberNumberField, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(serviceRenderedDateField, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(providerNumberField, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(serviceCodeField, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(dateRecordEnteredField, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(xProvider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(xMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(xService, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(xServiceRendered, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addGap(100, 100, 100))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dateRecordEnteredField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(serviceRenderedDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xServiceRendered))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(xProvider)
                    .addComponent(providerNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(memberNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xMember))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(xService)
                    .addComponent(serviceCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogServiceForm().setVisible(true);
            }
        });
    }

    @Action
    public void cancelButtonClicked() {
        dispose();
    }

    @Action
    public void nextButtonClicked() {
        boolean setReturn = false;
		
		if( serviceRenderedDateField.getText().equals("") ){
			xServiceRendered.setVisible(true);
			setReturn = true;
		}
		else
			xServiceRendered.setVisible(false);
		
		try {
			new Provider(((Number) this.providerNumberField.getValue()).intValue());
			xProvider.setVisible(false);
		} catch (Exception ex) {
			xProvider.setVisible(true);
			setReturn = true;
		}
		try {
			new Service(((Number) serviceCodeField.getValue()).intValue());
			xService.setVisible(false);
		} catch (Exception ex) {
			xService.setVisible(true);
			setReturn = true;
		}
		if( setReturn == true)
			return;
		

		
		try {
			ServiceRendered rendered = new ServiceRendered(
						now,
						(Date) (dateServiceRenderedField.getValue()),
						new Service(((Number) serviceCodeField.getValue()).intValue()).getFee(),
						new Provider(((Number) providerNumberField.getValue()).intValue()),
						new Service(((Number) serviceCodeField.getValue()).intValue()),
						new Member(((Number) memberNumberField.getValue()).intValue()),
						commentsField.getText()
						);
			final LogServiceConfirm logServiceForm;
			logServiceForm = new LogServiceConfirm(rendered);
					
			logServiceForm.setVisible(true);
			//logServiceForm.setFields(now, serviceRenderedDateField, providerNumberField, memberNumberField, serviceCodeField, commentsField);
			logServiceForm.addWindowListener(new WindowListener() {

				@Override
				public void windowClosed(WindowEvent e) {
					if( logServiceForm.recordCommitted() )
						dispose();
				}

				@Override
				public void windowOpened(WindowEvent e) {
				}

				@Override
				public void windowIconified(WindowEvent e) {
				}

				@Override
				public void windowDeiconified(WindowEvent e) {
				}

				@Override
				public void windowDeactivated(WindowEvent e) {
				}

				@Override
				public void windowClosing(WindowEvent e) {
				}

				@Override
				public void windowActivated(WindowEvent e) {
				}
			});
		} catch (Exception ex) {
			Logger.getLogger(LogServiceForm.class.getName()).log(Level.SEVERE, null, ex);
		}
		

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea commentsField;
    private javax.swing.JFormattedTextField dateRecordEnteredField;
    private javax.swing.JFormattedTextField dateServiceRenderedField;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField memberNumberField;
    private javax.swing.JFormattedTextField providerNumberField;
    private javax.swing.JFormattedTextField serviceCodeField;
    private javax.swing.JFormattedTextField serviceRenderedDateField;
    private javax.swing.JLabel xMember;
    private javax.swing.JLabel xProvider;
    private javax.swing.JLabel xService;
    private javax.swing.JLabel xServiceRendered;
    // End of variables declaration//GEN-END:variables

}
