/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ServiceList.java
 *
 * Created on Feb 7, 2011, 7:13:14 PM
 */

package border;

import java.util.Arrays;
import java.util.List;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import org.jdesktop.application.Action;

import com.sun.xml.internal.bind.v2.runtime.unmarshaller.XsiNilLoader.Array;

import entity.Provider;
import entity.Service;

/**
 * 
 * @author Brandon
 */
public class ServiceList extends javax.swing.JFrame {

	/** Creates new form ServiceList */
	public ServiceList() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jLabel1 = new javax.swing.JLabel();
		addButton = new javax.swing.JButton();
		searchField = new javax.swing.JTextField();
		editButton = new javax.swing.JButton();
		deleteButton1 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(pdx.edu.cs300_group9.DesktopApplication2.class).getContext().getResourceMap(ServiceList.class);
		setTitle(resourceMap.getString("Form.title")); // NOI18N
		setName("Form"); // NOI18N
		addWindowFocusListener(new java.awt.event.WindowFocusListener() {
			public void windowGainedFocus(java.awt.event.WindowEvent evt) {
				formWindowGainedFocus(evt);
			}
			public void windowLostFocus(java.awt.event.WindowEvent evt) {
			}
		});

		jScrollPane1.setName("jScrollPane1"); // NOI18N

		
		drawTable();
		/*jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object [][] {
						{"Doctor", "123456", "$$$$$$.$$"},
						{"Therapist", "987654321", "$$$$$$.$$"},
						{null, "", null},
						{null, null, null},
						{null, null, null},
						{null, null, null},
						{null, null, null},
						{null, null, null},
						{null, null, null},
						{null, null, null},
						{null, null, null},
						{null, null, null},
						{null, null, null},
						{null, null, null},
						{null, null, null},
						{null, null, null},
						{null, null, null},
						{null, null, null},
						{null, null, null},
						{null, null, null}
				},
				new String [] {
						"Service Name", "Service Number", "Fee "
				}
		));
		jTable1.setName("jTable1"); // NOI18N
		
		jScrollPane1.setViewportView(jTable1);
		*/

		jLabel1.setName("jLabel1"); // NOI18N

		javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(pdx.edu.cs300_group9.DesktopApplication2.class).getContext().getActionMap(ServiceList.class, this);
		addButton.setAction(actionMap.get("addButtonClicked")); // NOI18N
		addButton.setText(resourceMap.getString("addButton.text")); // NOI18N
		addButton.setName("addButton"); // NOI18N

		searchField.setText(resourceMap.getString("searchField.text")); // NOI18N
		searchField.setName("searchField"); // NOI18N
		searchField.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyReleased(java.awt.event.KeyEvent evt) {
				searchFieldKeyReleased(evt);
			}

		});

		editButton.setAction(actionMap.get("editButtonClicked")); // NOI18N
		editButton.setText(resourceMap.getString("editButton.text")); // NOI18N
		editButton.setName("editButton"); // NOI18N

		deleteButton1.setAction(actionMap.get("deleteButtonClicked")); // NOI18N
		deleteButton1.setText(resourceMap.getString("deleteButton1.text")); // NOI18N
		deleteButton1.setName("deleteButton1"); // NOI18N

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(addButton)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(editButton)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(deleteButton1)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
						.addComponent(jLabel1)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap())
						.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(layout.createSequentialGroup()
										.addContainerGap()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(addButton)
												.addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(deleteButton1)
												.addComponent(editButton)))
												.addComponent(jLabel1, 0, 0, Short.MAX_VALUE))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
		);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
		drawTable();
	}//GEN-LAST:event_formWindowGainedFocus

	private void searchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyReleased
		drawTable();
	}//GEN-LAST:event_searchFieldKeyReleased
	
	private void drawTable(){
		
		Vector<Vector<Object>> rows = new Vector<Vector<Object>>();
		
		List<Service> services;
		try {
			services = Service.getServices(searchField.getText());
			for( Service service : services ){
				rows.add(new Vector<Object>( Arrays.asList(new Object[]{
						service.getServiceName(),
						new Integer(service.getServiceId()),
						service.getFee()
				})));
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		DefaultTableModel model = new DefaultTableModel();
		
		model.setDataVector(rows, new Vector<String>( Arrays.asList(new String[]{"Service Name","Service Code","Service Fee"})));
		
		jTable1.getTableHeader().setReorderingAllowed(false);
		jTable1.setModel(model);
		jTable1.setName("jTable1");
		jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		jScrollPane1.setViewportView(jTable1);
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ServiceList().setVisible(true);
			}
		});
	}

	@Action
	public void addButtonClicked() {
		ServiceForm serviceForm = new ServiceForm();
		serviceForm.setVisible(true);
	}

	@Action
	public void editButtonClicked() {
		int col = jTable1.getSelectedColumn();
		int row = jTable1.getSelectedRow();
		if(row >= 0){
			int val = (Integer) jTable1.getValueAt(row, 1);
			ServiceForm serviceForm = new ServiceForm(val);
			serviceForm.setVisible(true);
		}
	}

	@Action
	public void deleteButtonClicked() {
		int row = jTable1.getSelectedRow();
		int val = (Integer) jTable1.getValueAt(row, 1);
		int response = JOptionPane.showConfirmDialog(null, "Delete Service: " + jTable1.getValueAt(row, 0));
		if( response == JOptionPane.YES_OPTION ){
			Service serv;
			try {
				serv = new Service(val);
				serv.delete();
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			drawTable();
		}
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton addButton;
	private javax.swing.JButton deleteButton1;
	private javax.swing.JButton editButton;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextField searchField;
	// End of variables declaration//GEN-END:variables

}
